export const SET_TOKEN='SET_TOKEN';
export const SET_TOKEN2='SET_TOKEN2';
export const SET_USER='SET_USER'; 
export const SIGNUP_START='SIGNUP_START'; 
export const SIGNUP_SUCCESS='SIGNUP_SUCCESS'; 
export const SIGNUP_FAILURE='SIGNUP_FAILURE'; 
export const LOGIN_START='LOGIN_START'; 
export const LOGIN_SUCCESS='LOGIN_SUCCESS'; 
export const LOGIN_FAILURE='LOGIN_FAILURE'; 
export const FORGETPASSWORD_START ='FORGETPASSWORD_START'; 
export const FORGETPASSWORD_SUCCESS='FORGETPASSWORD_SUCCESS'; 
export const FORGETPASSWORD_FAILURE='FORGETPASSWORD_FAILURE';
export const RESETPASSWORD_START ='RESETPASSWORD_START'; 
export const RESETPASSWORD_SUCCESS='RESETPASSWORD_SUCCESS'; 
export const RESETPASSWORD_FAILURE='RESETPASSWORD_FAILURE';
export const RULES_START='RULES_START'; 
export const RULES_SUCCESS='RULES_SUCCESS'; 
export const RULES_FAILURE='RULES_FAILURE'; 
export const CONFIRM_START='CONFIRM_START'; 
export const CONFIRM_SUCCESS=' CONFIRM_SUCCESS'; 
export const CONFIRM_FAILURE='CONFIRM_FAILURE'; 
export const RESWNDCODE_START='RESWNDCODE_START'; 
export const RESENDCODE_SUCCESS='RESENDCODE_SUCCESS'; 
export const RESENDCODE_FAILURE ='RESENDCODE_FAILURE';
export const RULESDOCTOR_START='RULESDOCTOR_START'
export const RULESDOCTOR_SUCCESS='RULESDOCTOR_SUCCESS'
export const RULESDOCTOR_FAILURE='RULESDOCTOR_FAILURE'
export const RULESPATIENT_START ='RULESPATIENT_START'
export const RULESPATIENT_SUCCESS='RULESPATIENT_SUCCESS'
export const RULESPATIENT_FAILURE='RULESPATIENT_FAILURE'
export const CLEAR_REDUX_DATA='CLEAR_REDUX_DATA';

export const AllDoctorsData_START ='AllDoctorsData_START'
export const AllDoctorsData_SUCCESS='AllDoctorsData_SUCCESS'
export const AllDoctorsData_FAILURE='AllDoctorsData_FAILURE'


